### PR TITLE
feat: replace Litestar SQLAdmin with SQLAdminPlugin.

### PR DESCRIPTION
**Pull request by rafalkrupinski**
Following  sqladmin-litestar [readme](https://github.com/cemrehancavdar/sqladmin-litestar), replace the link with sqladmin-litestar-plugin.

### CODE REVIEW

**Comment by rafalkrupinski** [comment]
BTW, there is a whole bunch of changes coming from pre-commit hook. Am I the first to actually run it? :D

**Comment by rafalkrupinski** [comment]
BTW2 There's a whole bunch of python-specific hooks that require download and slow down the first commit.
Also, is it necessary to check links both in pre-commit and GHA?

**Review by JacobCoffee — APPROVED** [review]
sorry for the delay, wanted to check with the other author to ensure they wanted to just show this one or keep  both

**Comment by JacobCoffee** [comment]
@rafalkrupinski i dont think so, but ill check out this repo and see what its doing when i get get settled w/ new job. probably just needs some tlc and feeding :D

**Pull request merged**
